spring.application.name=banking-ledger

# JPA / PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banking_db}
spring.datasource.username=${DB_USER:bank}
spring.datasource.password=${DB_PASS:bank_pass}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Kafka (Cloud Stream)
spring.cloud.stream.kafka.binder.brokers=${KAFKA_BOOTSTRAP:localhost:9092}
spring.cloud.stream.kafka.binder.auto-create-topics=false
spring.cloud.stream.default.content-type=application/json

# Logging
logging.level.com.corebanking=INFO
logging.level.org.hibernate.SQL=WARN
