spring.application.name=banking-account

# JPA / PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banking_db}
spring.datasource.username=${DB_USER:bank}
spring.datasource.password=${DB_PASS:bank_pass}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

# Kafka (Cloud Stream)
spring.cloud.stream.kafka.binder.brokers=${KAFKA_BOOTSTRAP:localhost:9092}
spring.cloud.stream.kafka.binder.auto-create-topics=false
spring.cloud.stream.default.content-type=application/json

# Cloud Stream — Output only (account publishes events)
spring.cloud.stream.bindings.eventPublisher-output.destination=banking.events
spring.cloud.stream.bindings.eventPublisher-output.content-type=application/json
spring.cloud.stream.kafka.binder.configuration.acks=all
spring.cloud.stream.kafka.binder.configuration.enable.idempotence=true
spring.cloud.stream.kafka.binder.configuration.max.in.flight.requests.per.connection=1
spring.cloud.stream.source=eventPublisher

# Logging
logging.level.com.corebanking=INFO
logging.level.org.hibernate.SQL=WARN
